
export const API_ENDPOINTS = {
  LOOKUP: '/api/lookup',
  PROXY_IMAGE: '/api/proxy-image',
  GEMINI: '/api/gemini',
};

export const LANGUAGES = {
  en: 'English',
  zh: '中文',
  ja: '日本語',
  fr: 'Français'
} as const;

export type Language = keyof typeof LANGUAGES;

export const TRANSLATIONS = {
  en: {
    appTitle: 'AI GUEST BOOK WALL.',
    subtitlePrefix: 'A ',
    subtitleSuffix: ' Owned System',
    addGuest: 'Add Guest',
    gameRules: 'Game Rules',
    page: 'PAGE',
    enterHandle: 'Enter handle...',
    igIdentity: 'Instagram Identity',
    pressEnter: 'PRESS ENTER',
    analyzing: 'We will display your account to facilitate connections and expand your social network.',
    geminiTitle: 'Gemini Intelligence',
    analyzingLoader: 'ANALYZING ACCOUNT...',
    unavailable: 'Analysis unavailable.',
    personality: 'Personality',
    career: 'Career',
    lifestyle: 'Lifestyle',
    id: 'ID',
    system: 'AI GUEST BOOK WALL v2.0',
    // Correction Flow
    inaccurate: 'Inaccurate? Correct Analysis.',
    identityCheck: 'IDENTITY VERIFICATION',
    legalWarning: 'Are you the owner of this account? Providing false information implies legal responsibility.',
    yesOwner: 'YES, I AM THE OWNER',
    cancel: 'CANCEL',
    correctionLabel: 'Provide correct context (Profession, Vibe, etc.)',
    regenerate: 'UPDATE ANALYSIS',
    userVerified: 'USER VERIFIED INPUT',
    unknown: 'Unknown',
    // Admin
    adminMode: 'Admin Mode',
    exitAdmin: 'Exit Admin',
    enterPassword: 'Enter Password...',
    passwordPlaceholder: '******',
    wrongPassword: 'Access Denied.',
    confirmExit: 'Are you sure you want to exit Admin Mode?',
    confirm: 'Confirm',
    deleteGuest: 'DELETE'
  },
  zh: {
    appTitle: 'AI 嘉宾墙.',
    subtitlePrefix: '',
    subtitleSuffix: ' 旗下系统',
    addGuest: '添加嘉宾',
    gameRules: '游戏规则',
    page: '页码',
    enterHandle: '输入用户名...',
    igIdentity: 'Instagram 身份',
    pressEnter: '按回车键',
    analyzing: '我们将向大家展示您的社交媒体账号，方便其他嘉宾添加您，扩展社交交际网络。',
    geminiTitle: 'Gemini 智能分析',
    analyzingLoader: '正在分析账户...',
    unavailable: '暂时无法分析。',
    personality: '性格',
    career: '职业',
    lifestyle: '生活方式',
    id: '编号',
    system: 'AI 智能迎宾墙 v2.0',
    // Correction Flow
    inaccurate: '不准确？更正信息。',
    identityCheck: '身份核验',
    legalWarning: '您是该账户本人吗？提供虚假信息需承担法律责任。',
    yesOwner: '是，我是本人',
    cancel: '取消',
    correctionLabel: '提供真实信息 (职业、性格等)',
    regenerate: '更新分析报告',
    userVerified: '基于用户手动输入',
    unknown: '未知',
    // Admin
    adminMode: '管理员模式',
    exitAdmin: '退出管理',
    enterPassword: '请输入管理员密码...',
    passwordPlaceholder: '******',
    wrongPassword: '密码错误。',
    confirmExit: '确定退出管理员模式吗？',
    confirm: '确定',
    deleteGuest: '删除'
  },
  ja: {
    appTitle: 'AI ゲストブックウォール.',
    subtitlePrefix: '',
    subtitleSuffix: ' 所有システム',
    addGuest: 'ゲスト追加',
    gameRules: 'ゲームルール',
    page: 'ページ',
    enterHandle: 'IDを入力...',
    igIdentity: 'Instagram ID',
    pressEnter: 'Enterキー',
    analyzing: '他のゲストがあなたを追加し、ソーシャルネットワークを広げやすくするために、あなたのアカウントを表示します。',
    geminiTitle: 'Gemini インテリジェンス',
    analyzingLoader: 'アカウント分析中...',
    unavailable: '分析できません。',
    personality: '性格',
    career: '職業',
    lifestyle: 'ライフスタイル',
    id: 'ID',
    system: 'AI ゲストブックウォール v2.0',
    // Correction Flow
    inaccurate: '不正確ですか？修正する。',
    identityCheck: '本人確認',
    legalWarning: 'あなたはこのアカウントの所有者ですか？虚偽の情報提供は法的責任を伴います。',
    yesOwner: 'はい、本人です',
    cancel: 'キャンセル',
    correctionLabel: '正しい情報を入力 (職業、雰囲気など)',
    regenerate: '分析を更新',
    userVerified: 'ユーザー入力に基づく',
    unknown: '不明',
    // Admin
    adminMode: '管理者モード',
    exitAdmin: '管理終了',
    enterPassword: 'パスワードを入力...',
    passwordPlaceholder: '******',
    wrongPassword: 'アクセス拒否。',
    confirmExit: '管理者モードを終了しますか？',
    confirm: '確認',
    deleteGuest: '削除'
  },
  fr: {
    appTitle: 'MUR D\'INVITÉS IA.',
    subtitlePrefix: 'Un système appartenant à ',
    subtitleSuffix: '',
    addGuest: 'Ajouter',
    gameRules: 'Règles du jeu',
    page: 'PAGE',
    enterHandle: 'Entrez le pseudo...',
    igIdentity: 'Identité Instagram',
    pressEnter: 'APPUYEZ SUR ENTRÉE',
    analyzing: 'Nous afficherons votre compte pour faciliter les connexions et étendre votre réseau social.',
    geminiTitle: 'Intelligence Gemini',
    analyzingLoader: 'ANALYSE DU COMPTE...',
    unavailable: 'Analyse indisponible.',
    personality: 'Personnalité',
    career: 'Carrière',
    lifestyle: 'Style de vie',
    id: 'ID',
    system: 'MUR D\'INVITÉS IA v2.0',
    // Correction Flow
    inaccurate: 'Inexact ? Corriger.',
    identityCheck: 'VÉRIFICATION D\'IDENTITÉ',
    legalWarning: 'Êtes-vous le propriétaire de ce compte ? Fournir de fausses informations implique une responsabilité légale.',
    yesOwner: 'OUI, JE SUIS LE PROPRIÉTAIRE',
    cancel: 'ANNULER',
    correctionLabel: 'Fournir le contexte correct',
    regenerate: 'METTRE À JOUR',
    userVerified: 'VÉRIFIÉ PAR L\'UTILISATEUR',
    unknown: 'Inconnu',
    // Admin
    adminMode: 'Mode Admin',
    exitAdmin: 'Quitter Admin',
    enterPassword: 'Mot de passe...',
    passwordPlaceholder: '******',
    wrongPassword: 'Accès refusé.',
    confirmExit: 'Voulez-vous quitter le mode Admin ?',
    confirm: 'Confirmer',
    deleteGuest: 'SUPPRIMER'
  }
};
